apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
namespace: demo-dev
images:
- name: uuvtqd/gitops-webapp
  newTag: 5357c3501608a930ee4c7bdc1d34b3468b854874


# Not all Resources or fields support strategic merge patches. 
# To support modifying arbitrary fields in arbitrary Resources, 
# Kustomize offers applying JSON patch through patchesJson6902. 
# https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html
# patchesStrategicMerge:
# - custom-env.yaml

